/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;
import audio.TocarSom;
import comunicador.Comunicador;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Cássio e Frederico
 */
public class FrameChat extends javax.swing.JFrame {

    /**
     * Creates new form FrameCliente
     * @throws java.rmi.RemoteException
     */
    public FrameChat() throws RemoteException {
        initComponents();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCliente = new javax.swing.JPanel();
        fieldEndereco = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        fieldApelido = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();
        fieldMsg = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaChat = new javax.swing.JTextArea();
        fieldPorta = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHAT - MULTICAST - por Cássio e Frederico");
        setResizable(false);

        panelCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "CHAT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelCliente.setMaximumSize(new java.awt.Dimension(800, 600));
        panelCliente.setMinimumSize(new java.awt.Dimension(800, 600));

        fieldEndereco.setEditable(false);
        fieldEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldEndereco.setForeground(Color.gray);
        fieldEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Endereço:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btnEnviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnviar.setText("ENVIAR");
        btnEnviar.setEnabled(false);
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });

        fieldApelido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldApelido.setForeground(Color.gray);
        fieldApelido.setText("Digite seu apelido...");
        fieldApelido.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Apelido:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        fieldApelido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldApelidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldApelidoFocusLost(evt);
            }
        });

        btnConectar.setText("CONECTAR");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        fieldMsg.setText("Digite sua mensagem...");
        fieldMsg.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "SUA MENSAGEM:"));
        fieldMsg.setEnabled(false);
        fieldMsg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldMsgFocusGained(evt);
            }
        });
        fieldMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldMsgKeyPressed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "CHAT:"));

        txtAreaChat.setEditable(false);
        txtAreaChat.setColumns(20);
        txtAreaChat.setLineWrap(true);
        txtAreaChat.setRows(5);
        txtAreaChat.setToolTipText("");
        txtAreaChat.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAreaChat);

        fieldPorta.setEditable(false);
        fieldPorta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldPorta.setForeground(Color.gray);
        fieldPorta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Porta:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btnSair.setText("SAIR");
        btnSair.setEnabled(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelClienteLayout.createSequentialGroup()
                            .addComponent(fieldMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEnviar))
                        .addGroup(panelClienteLayout.createSequentialGroup()
                            .addComponent(fieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void fieldApelidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApelidoFocusGained
        // TODO add your handling code here:
        fieldApelidoIn();
    }//GEN-LAST:event_fieldApelidoFocusGained

    private void fieldApelidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApelidoFocusLost
        // TODO add your handling code here:
        fieldApelidoOut();
    }//GEN-LAST:event_fieldApelidoFocusLost

    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        // TODO add your handling code here:
        enviar();
    }//GEN-LAST:event_btnEnviarMouseClicked

    private void fieldMsgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldMsgFocusGained
        // TODO add your handling code here:
        fieldMsgIn();
    }//GEN-LAST:event_fieldMsgFocusGained

    private void fieldMsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMsgKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            enviar();
        }
    }//GEN-LAST:event_fieldMsgKeyPressed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        conectar();
    }//GEN-LAST:event_btnConectarActionPerformed
    
    /*Métodos*/
    TocarSom somMsgRecebida = new TocarSom("/audio/msn.wav");
    TocarSom somLogin = new TocarSom("/audio/entrar.wav");
    TocarSom somLogout = new TocarSom("/audio/sair.wav");
    //Thread Receptora
    class ThreadReceptora extends Thread {
        @Override
        public void run(){
            while(true){
                try{
                    DatagramPacket pacote = com.receberMensagem(socket);
                    String mensagemRecebida = new String(pacote.getData(), 0, pacote.getLength());
                    mensagens.add(mensagemRecebida);
                    Iterator i = mensagens.iterator(); //Interador da lista
                    txtAreaChat.setText("");
                    while(i.hasNext()){
                        txtAreaChat.append(i.next().toString() + "\n");
                    }
                    if((txtAreaChat.getLineCount() > 2) && (!mensagemRecebida.contains(fieldApelido.getText() + " saiu da sala."))){
                        somMsgRecebida.tocarSom();
                    }
                }catch(Exception e){
                    System.out.println(e);
                }
            }
        }
    }
    //Métodos referente aos eventos
    private void conectar(){
        fieldEndereco.setText("239.1.2.3"); //Define o IP
        fieldPorta.setText("3456"); //Define a porta
        
        try{
            if((fieldApelido.getText().equals("Digite seu apelido...")) || (fieldApelido.getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "Digite seu apelido...");
            }
            else{
                fieldMsg.setEnabled(true);
                btnEnviar.setEnabled(true);
                grupo = InetAddress.getByName(fieldEndereco.getText());//Define o ip
                socket = new MulticastSocket(Integer.parseInt(fieldPorta.getText()));//Define a porta e cria o socket
                socket.joinGroup(grupo);//Ingressa no grupo multicast
                ThreadReceptora threadRecep = new ThreadReceptora();
                threadRecep.start();
                btnConectar.setEnabled(false);
                btnSair.setEnabled(true);
                fieldApelido.setEnabled(false);
                String msg = fieldApelido.getText() + " entrou na sala";
                DatagramPacket pacote = com.montarMensagem(msg, fieldEndereco.getText(), Integer.parseInt(fieldPorta.getText()));
                socket.send(pacote);
                somLogin.tocarSom();
            }
        }catch(HeadlessException | IOException | NumberFormatException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Oh não! Aconteceu um erro na conexão :/");
        }
    }
    
    //Método para enviar
    private void enviar(){
        try {
            String msg = fieldApelido.getText() + " diz: "+fieldMsg.getText();
            DatagramPacket pacote = com.montarMensagem(msg, fieldEndereco.getText(), Integer.parseInt(fieldPorta.getText()));
            socket.send(pacote);
            fieldMsg.setText("");
        }
        catch (IOException ex) {
            Logger.getLogger(FrameChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //Método para sair
    private void sair(){
        try{
            String msg = fieldApelido.getText() + " saiu da sala.";
            DatagramPacket pacote = com.montarMensagem(msg, fieldEndereco.getText(), Integer.parseInt(fieldPorta.getText()));
            socket.send(pacote);
            btnConectar.setEnabled(true);
            btnSair.setEnabled(false);
            somLogout.tocarSom();
            fechaFrame();
        }
        catch(IOException ex){
            Logger.getLogger(FrameChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Fecha o frame
    private void fechaFrame(){
        try{
            Thread.sleep(2500);
            System.exit(0);
        }
        catch(InterruptedException e){
            System.out.println(e);
        }
    }
    
    //Apelido
    private void fieldApelidoIn(){
        fieldApelido.setForeground(Color.black);
        fieldApelido.setText("");
    }
    private void fieldApelidoOut(){
        if(fieldApelido.getText().equals("")){
            fieldApelido.setForeground(Color.gray);
            fieldApelido.setText("Digite seu apelido...");
        }
    }
    
    //Mensagem
    private void fieldMsgIn(){
        fieldMsg.setForeground(Color.black);
        fieldMsg.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameChat frmCliente;
                try {
                    frmCliente = new FrameChat();
                    frmCliente.setLocationRelativeTo(null);
                    frmCliente.setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(FrameChat.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }
    
    //Variaveis do multicast
    InetAddress grupo;
    MulticastSocket socket;
    Comunicador com = new Comunicador();
    LinkedList<String> mensagens = new LinkedList<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnSair;
    private javax.swing.JTextField fieldApelido;
    private javax.swing.JTextField fieldEndereco;
    private javax.swing.JTextField fieldMsg;
    private javax.swing.JTextField fieldPorta;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JTextArea txtAreaChat;
    // End of variables declaration//GEN-END:variables
}
